sudo: required
language: java


dist: trusty

cache:
  directories:
  - $HOME/.m2
      
script: 
# To run on production server
# - python run_unittests.py;
# To run on QA
- python run_unittests.py -s 'ws.binaryws.com' -a 1089 -t 'ei5EBsqQan230MG'  



before_install:
 - sudo pip install -r requirements.txt --ignore-installed six
 - sudo pip install websocket-client
 - sudo pip install argparse
 



  
after_script:
  - cat target/surefire-reports/TestSuite.txt
  
notifications:
  email:
    recipients:
      - meeyun@binary.com
    on_success: never
    on_failure: never
