sudo: required
language: java


dist: trusty

cache:
  directories:
  - $HOME/.m2
      
script: 
# To run on production server
 - python run_unittests.py;
# To run on QA (currently not working in travis. need to check)
# - python run_unittests.py -s 'www.binaryqa27.com' -a 1003 -t 'xxxxxxxxxxxxx'  



before_install:
 - sudo pip install -r requirements.txt --ignore-installed six
 - sudo pip install websocket-client




  
after_script:
  - cat target/surefire-reports/TestSuite.txt
  
notifications:
  email:
    recipients:
      - meeyun@binary.com
    on_success: never
    on_failure: always
