sudo: required
language: java


dist: trusty

cache:
  directories:
  - $HOME/.m2
      
script: 
# To run on production server
# - python run_unittests.py;
# To run on QA
- python run_unittests.py -s 'www.binaryqa27.com' -a 1003 -t 'lmmtw76c5gGAwvq'  



before_install:
 - sudo pip uninstall pyOpenSSL
 - sudo pip install -r requirements.txt --ignore-installed six
 - sudo pip install websocket-client
 - sudo apt-get install libffi-dev
 - sudo pip install pyOpenSSL ndg-httpsclient pyasn1 
 - sudo pip install pyopenssl ndg-httpsclient pyasn1
 - sudo pip install ndg-httpsclient pyasn1 --upgrade
 - sudo pip install requests[security]



  
after_script:
  - cat target/surefire-reports/TestSuite.txt
  
notifications:
  email:
    recipients:
      - meeyun@binary.com
    on_success: never
    on_failure: never
