sudo: required
language: java
dist: trusty

cache:
  directories:
  - $HOME/.m2
      
script:
 - python run_unittests.py --rerun 5;


before_install:
 - sudo pip install -r requirements.txt --ignore-installed six
 - sudo pip install websocket-client
 - sudo pip install pytest-rerunfailures
  
after_script:
  - cat target/surefire-reports/TestSuite.txt
  
notifications:
  email:
    recipients:
      - meeyun@binary.com
    on_success: never
    on_failure: always
