sudo: required
language: java
dist: trusty
cache:
  directories:
  - "$HOME/.m2"
script:
- python run_unittests.py;
before_install:
#- openssl aes-256-cbc -K $encrypted_5299dd8ed6f7_key -iv $encrypted_5299dd8ed6f7_iv
#  -in setting.py.enc -out test_utils/setting.py -d
- sudo pip install -r requirements.txt --ignore-installed six
- sudo pip install urllib3[secure]
- sudo pip install websocket-client
after_script:
- cat target/surefire-reports/TestSuite.txt
notifications:
  email:
    recipients:
    - meeyun@binary.com
    - my_choong11@hotmail.com
    on_success: never
    on_failure: always
